import React, { useState } from 'react';
import { 
  FileCode2, 
  Plus, 
  Trash2, 
  Save, 
  Check, 
  Copy, 
  Code2, 
  Layers, 
  ShieldCheck,
  Sparkles
} from 'lucide-react';
import { DocTypeMeta, DocField, DocFieldType } from '../../types/erp';
import { frappeDB } from '../../framework/db';

const FIELD_TYPES: DocFieldType[] = [
  'Data',
  'Int',
  'Float',
  'Currency',
  'Date',
  'Select',
  'Link',
  'Text',
  'Check',
];

interface DocTypeBuilderProps {
  onDocTypeCreated: (meta: DocTypeMeta) => void;
}

export const DocTypeBuilder: React.FC<DocTypeBuilderProps> = ({ onDocTypeCreated }) => {
  const [selectedExisting, setSelectedExisting] = useState<string>('NEW');
  const [name, setName] = useState('Supplier');
  const [module, setModule] = useState<'Core' | 'Sales' | 'Stock' | 'Accounting' | 'HR' | 'Projects' | 'Custom'>('Custom');
  const [description, setDescription] = useState('Vendor accounts supplying raw materials and industrial services');
  const [autonamePrefix, setAutonamePrefix] = useState('SUPP-');
  const [titleField, setTitleField] = useState('supplier_name');
  const [isSubmittable, setIsSubmittable] = useState(false);

  const [fields, setFields] = useState<DocField[]>([
    { fieldname: 'supplier_name', label: 'Supplier Name', fieldtype: 'Data', reqd: true, in_list_view: true },
    { fieldname: 'supplier_type', label: 'Supplier Type', fieldtype: 'Select', options: 'Manufacturer,Distributor,Service Provider', default: 'Manufacturer', in_list_view: true },
    { fieldname: 'contact_email', label: 'Contact Email', fieldtype: 'Data', in_list_view: true },
    { fieldname: 'country', label: 'Country of Origin', fieldtype: 'Data', default: 'United States', in_list_view: true },
    { fieldname: 'credit_rating', label: 'Credit Rating', fieldtype: 'Select', options: 'AAA,AA,A,BBB,B', default: 'AAA', in_list_view: true },
    { fieldname: 'payment_terms_days', label: 'Payment Terms (Days)', fieldtype: 'Int', default: 30 },
  ]);

  const [activeCodeView, setActiveCodeView] = useState<'python' | 'json'>('python');
  const [saveSuccess, setSaveSuccess] = useState(false);

  const allDocTypes = frappeDB.get_all_doctypes();

  const handleSelectExisting = (dtName: string) => {
    setSelectedExisting(dtName);
    if (dtName === 'NEW') {
      setName('Quality Inspection');
      setModule('Custom');
      setDescription('Routine QA checkpoint testing log for incoming shipments');
      setAutonamePrefix('QA-');
      setTitleField('inspection_name');
      setIsSubmittable(true);
      setFields([
        { fieldname: 'inspection_name', label: 'Inspection Title', fieldtype: 'Data', reqd: true, in_list_view: true },
        { fieldname: 'inspection_date', label: 'Inspection Date', fieldtype: 'Date', reqd: true, in_list_view: true },
        { fieldname: 'item_code', label: 'Item Inspected', fieldtype: 'Link', options: 'Item', reqd: true, in_list_view: true },
        { fieldname: 'batch_no', label: 'Batch / Lot #', fieldtype: 'Data', in_list_view: true },
        { fieldname: 'sample_size', label: 'Sample Units', fieldtype: 'Int', default: 5 },
        { fieldname: 'status', label: 'Status', fieldtype: 'Select', options: 'Accepted,Rejected,Quarantine', default: 'Accepted', in_list_view: true },
      ]);
    } else {
      const dt = frappeDB.get_doctype(dtName);
      if (dt) {
        setName(dt.name);
        setModule(dt.module);
        setDescription(dt.description);
        setAutonamePrefix(dt.autoname_prefix || 'DOC-');
        setTitleField(dt.title_field || 'name');
        setIsSubmittable(!!dt.is_submittable);
        setFields([...dt.fields]);
      }
    }
  };

  const addField = () => {
    const newF: DocField = {
      fieldname: `custom_field_${fields.length + 1}`,
      label: `Field ${fields.length + 1}`,
      fieldtype: 'Data',
      in_list_view: true,
    };
    setFields([...fields, newF]);
  };

  const removeField = (index: number) => {
    setFields(fields.filter((_, i) => i !== index));
  };

  const updateField = (index: number, key: keyof DocField, value: any) => {
    const updated = [...fields];
    updated[index] = { ...updated[index], [key]: value };
    // Auto sync fieldname from label
    if (key === 'label' && !updated[index].fieldname.startsWith('custom_')) {
      updated[index].fieldname = String(value).toLowerCase().replace(/[^a-z0-9_]/g, '_');
    }
    setFields(updated);
  };

  // Generate Python Controller
  const generatedPython = `# -*- coding: utf-8 -*-
# Auto-generated by AetherERP Meta Engine
from frappe.model.document import Document
import frappe

class ${name.replace(/\s+/g, '')}(Document):
    """
    ${description}
    Module: ${module}
    """
    def validate(self):
        # Enforce business rules before persistence
        ${fields.filter(f => f.reqd).map(f => `if not self.${f.fieldname}:\n            frappe.throw("${f.label} is mandatory")`).join('\n        ') || 'pass'}

    ${isSubmittable ? `def on_submit(self):
        # Workflow submission hook
        frappe.msgprint(f"${name} {self.name} has been formally submitted.")

    def on_cancel(self):
        # Rollback or reversal logic
        pass` : ''}
`;

  // Generate JSON Metadata
  const generatedJson = JSON.stringify(
    {
      doctype: 'DocType',
      name,
      module,
      description,
      autoname_prefix: autonamePrefix,
      title_field: titleField,
      is_submittable: isSubmittable,
      fields,
      permissions: [
        { role: 'System Manager', read: true, write: true, create: true, delete: true, submit: isSubmittable, cancel: isSubmittable },
        { role: 'Stock User', read: true, write: true, create: true, delete: false, submit: false, cancel: false },
      ],
    },
    null,
    2
  );

  const handleSaveDocType = () => {
    const meta: DocTypeMeta = {
      name,
      module,
      description,
      autoname_prefix: autonamePrefix,
      title_field: titleField,
      is_submittable: isSubmittable,
      fields,
      permissions: [
        { role: 'System Manager', read: true, write: true, create: true, delete: true, submit: isSubmittable, cancel: isSubmittable },
        { role: 'Stock User', read: true, write: true, create: true, delete: false, submit: false, cancel: false },
        { role: 'Sales Manager', read: true, write: false, create: false, delete: false, submit: false, cancel: false },
        { role: 'Accounts Manager', read: true, write: false, create: false, delete: false, submit: false, cancel: false },
        { role: 'HR Manager', read: false, write: false, create: false, delete: false, submit: false, cancel: false },
      ],
      python_controller: generatedPython,
    };

    frappeDB.save_doctype(meta);
    setSaveSuccess(true);
    setTimeout(() => setSaveSuccess(false), 2500);
    onDocTypeCreated(meta);
  };

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 pb-6 border-b border-slate-200">
        <div>
          <div className="flex items-center gap-2 text-xs text-slate-500 mb-1">
            <span>Framework Engine</span>
            <span aria-hidden="true">/</span>
            <span className="font-semibold text-slate-700">Database Abstraction</span>
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-slate-900">
            DocType Schema Architect
          </h1>
          <p className="text-sm text-slate-500 mt-1">
            Meta-data driven schema system. Changes instantly synchronize across Python controllers, REST endpoints, and UI forms.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <select
            value={selectedExisting}
            onChange={(e) => handleSelectExisting(e.target.value)}
            className="px-3 py-2 text-xs bg-white border border-slate-200 rounded-lg text-slate-700 focus:outline-none"
          >
            <option value="NEW">+ Design New DocType</option>
            <optgroup label="Core DocTypes">
              {allDocTypes.map((dt) => (
                <option key={dt.name} value={dt.name}>
                  Inspect: {dt.name} ({dt.module})
                </option>
              ))}
            </optgroup>
          </select>

          <button
            onClick={handleSaveDocType}
            className="flex items-center gap-1.5 px-4 py-2 text-xs font-semibold text-white bg-slate-900 rounded-lg hover:bg-slate-800 transition-colors shadow-sm"
          >
            {saveSuccess ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span>DocType Synced!</span>
              </>
            ) : (
              <>
                <Save className="w-3.5 h-3.5" />
                <span>Save Schema & Controllers</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Main Grid: Schema Definition on Left, Code Output on Right */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column: Schema Config & Field Builder (7 cols) */}
        <div className="lg:col-span-7 space-y-6">
          {/* Metadata Card */}
          <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs space-y-4">
            <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
              DocType Core Properties
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="text-xs font-semibold text-slate-700">DocType Name</label>
                <input
                  type="text"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="mt-1 w-full px-3 py-1.5 text-xs bg-white border border-slate-200 rounded-md focus:outline-none focus:border-slate-400"
                />
              </div>

              <div>
                <label className="text-xs font-semibold text-slate-700">Module</label>
                <select
                  value={module}
                  onChange={(e) => setModule(e.target.value as any)}
                  className="mt-1 w-full px-3 py-1.5 text-xs bg-white border border-slate-200 rounded-md focus:outline-none focus:border-slate-400"
                >
                  <option value="Custom">Custom</option>
                  <option value="Core">Core</option>
                  <option value="Sales">Sales</option>
                  <option value="Stock">Stock</option>
                  <option value="Accounting">Accounting</option>
                  <option value="HR">HR</option>
                  <option value="Projects">Projects</option>
                </select>
              </div>

              <div>
                <label className="text-xs font-semibold text-slate-700">Autoname Prefix</label>
                <input
                  type="text"
                  value={autonamePrefix}
                  onChange={(e) => setAutonamePrefix(e.target.value)}
                  className="mt-1 w-full px-3 py-1.5 text-xs font-mono bg-white border border-slate-200 rounded-md focus:outline-none focus:border-slate-400"
                />
              </div>

              <div className="flex items-center pt-5">
                <label className="flex items-center gap-2 cursor-pointer select-none">
                  <input
                    type="checkbox"
                    checked={isSubmittable}
                    onChange={(e) => setIsSubmittable(e.target.checked)}
                    className="rounded border-slate-300 text-slate-900 focus:ring-slate-900"
                  />
                  <span className="text-xs font-semibold text-slate-700">Is Submittable (Document Lifecycle)</span>
                </label>
              </div>
            </div>

            <div>
              <label className="text-xs font-semibold text-slate-700">Description</label>
              <input
                type="text"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                className="mt-1 w-full px-3 py-1.5 text-xs bg-white border border-slate-200 rounded-md focus:outline-none focus:border-slate-400"
              />
            </div>
          </div>

          {/* Fields Builder */}
          <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
                  Field Definitions ({fields.length})
                </h3>
                <p className="text-[11px] text-slate-500">Columns mapped to Database Abstraction Layer</p>
              </div>
              <button
                onClick={addField}
                className="flex items-center gap-1 px-2.5 py-1 text-xs font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-md transition-colors"
              >
                <Plus className="w-3 h-3" />
                <span>Add Field</span>
              </button>
            </div>

            <div className="space-y-3">
              {fields.map((f, idx) => (
                <div
                  key={idx}
                  className="p-3 bg-slate-50 rounded-lg border border-slate-200 grid grid-cols-12 gap-2.5 items-center"
                >
                  <div className="col-span-3">
                    <label className="text-[10px] text-slate-500 block font-semibold">Label</label>
                    <input
                      type="text"
                      value={f.label}
                      onChange={(e) => updateField(idx, 'label', e.target.value)}
                      className="w-full px-2 py-1 text-xs bg-white border border-slate-200 rounded focus:outline-none"
                    />
                  </div>

                  <div className="col-span-3">
                    <label className="text-[10px] text-slate-500 block font-semibold">Fieldname</label>
                    <input
                      type="text"
                      value={f.fieldname}
                      onChange={(e) => updateField(idx, 'fieldname', e.target.value)}
                      className="w-full px-2 py-1 text-xs font-mono bg-white border border-slate-200 rounded focus:outline-none text-slate-700"
                    />
                  </div>

                  <div className="col-span-2">
                    <label className="text-[10px] text-slate-500 block font-semibold">Type</label>
                    <select
                      value={f.fieldtype}
                      onChange={(e) => updateField(idx, 'fieldtype', e.target.value)}
                      className="w-full px-1.5 py-1 text-xs bg-white border border-slate-200 rounded focus:outline-none"
                    >
                      {FIELD_TYPES.map((t) => (
                        <option key={t} value={t}>
                          {t}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="col-span-3 flex items-center gap-3 pt-3">
                    <label className="flex items-center gap-1 text-[11px] text-slate-600 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={!!f.reqd}
                        onChange={(e) => updateField(idx, 'reqd', e.target.checked)}
                        className="rounded border-slate-300 text-slate-900"
                      />
                      <span>Reqd</span>
                    </label>

                    <label className="flex items-center gap-1 text-[11px] text-slate-600 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={!!f.in_list_view}
                        onChange={(e) => updateField(idx, 'in_list_view', e.target.checked)}
                        className="rounded border-slate-300 text-slate-900"
                      />
                      <span>In List</span>
                    </label>
                  </div>

                  <div className="col-span-1 text-right pt-3">
                    <button
                      onClick={() => removeField(idx)}
                      className="text-slate-400 hover:text-rose-600 p-1 transition-colors"
                      title="Remove Field"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>

                  {(f.fieldtype === 'Select' || f.fieldtype === 'Link') && (
                    <div className="col-span-12 pt-1 border-t border-slate-200/60 mt-1 flex items-center gap-2">
                      <span className="text-[10px] font-semibold text-slate-500 uppercase">
                        {f.fieldtype === 'Select' ? 'Options (comma separated):' : 'Target DocType:'}
                      </span>
                      <input
                        type="text"
                        value={f.options || ''}
                        onChange={(e) => updateField(idx, 'options', e.target.value)}
                        placeholder={f.fieldtype === 'Select' ? 'Option 1,Option 2,Option 3' : 'Target DocType e.g. Customer'}
                        className="flex-1 px-2 py-0.5 text-xs bg-white border border-slate-200 rounded focus:outline-none"
                      />
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right Column: Code & Model Generation Preview (5 cols) */}
        <div className="lg:col-span-5 space-y-4">
          <div className="bg-slate-900 rounded-xl overflow-hidden shadow-md border border-slate-800 flex flex-col h-full">
            {/* Tab switch */}
            <div className="px-4 py-3 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setActiveCodeView('python')}
                  className={`px-3 py-1 text-xs font-semibold rounded-md transition-colors ${
                    activeCodeView === 'python'
                      ? 'bg-slate-800 text-white'
                      : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  Python Controller
                </button>
                <button
                  onClick={() => setActiveCodeView('json')}
                  className={`px-3 py-1 text-xs font-semibold rounded-md transition-colors ${
                    activeCodeView === 'json'
                      ? 'bg-slate-800 text-white'
                      : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  DocType JSON Schema
                </button>
              </div>

              <button
                onClick={() => {
                  navigator.clipboard.writeText(
                    activeCodeView === 'python' ? generatedPython : generatedJson
                  );
                }}
                title="Copy to clipboard"
                className="text-slate-400 hover:text-white p-1 transition-colors"
              >
                <Copy className="w-4 h-4" />
              </button>
            </div>

            {/* Code Box */}
            <div className="p-4 flex-1 overflow-auto max-h-[560px]">
              <pre className="text-xs font-mono text-emerald-300 leading-relaxed">
                <code>{activeCodeView === 'python' ? generatedPython : generatedJson}</code>
              </pre>
            </div>

            <div className="p-3 bg-slate-950/80 border-t border-slate-800 text-[11px] text-slate-400 flex items-center justify-between">
              <span>Auto-generated backend controller</span>
              <span className="font-mono text-slate-300">Frappe Python Syntax</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
